# Account 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNTM5NjE3LCJleHAiOjE3MjE1NDY4MTd9.ymtNVJiLvOXPL3Zg7suOT3HVYhnBkBiq-2XxP2YnxzysnKtvTSYfkkB9i5zHwgF0v57qo6y_FBzuF36kOONFpw

### register account
POST http://localhost:8080/api/v1/account?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "accountNumber": "1234-4444",
  "balance": 11114
}

### get member accounts
GET http://localhost:8080/api/v1/account?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### modify account Information
GET http://localhost:8080/api/v1/account
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111"
}

### unregister account
DELETE http://localhost:8080/api/v1/account
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111"
}