# Member 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNjE4NjczLCJleHAiOjE3MjE2MjU4NzN9.mvkyrk6Uu8G5ehmRaNR0X5ZRCLdz6nqND93-TjWgg14-V_jqw9Qn9wDvdbHeYs0tF2X3WGNbPZUUTJ4UXlx4hQ

### get member accounts
GET http://localhost:8080/api/v1/account?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
