# Member 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNjEyMTEwLCJleHAiOjE3MjE2MTkzMTB9.dIE9mnxj9-E5muTj_UagVBudSOjs-QYFivSPSc2kgjAML6VR7eEFaT2-oXYdAvdViPGNdCwoLPOWr07ysDIYYw

### get member accounts
GET http://localhost:8080/api/v1/account?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
