# Member 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNDgwMjY5LCJleHAiOjE3MjE0ODc0Njl9.AsWs4Z1gPZZsoeXbJ7A26aSm-6VQYFnFT2E2WqmaG1U6K-NuJzoUMEQdtCvU-Ss7tICs54pZAvLNlrpfTl6pgg

### get member accounts
GET http://localhost:8080/api/v1/account?member_id=2
Content-Type: application/json
Authorization: Bearer {{accessToken}}
