# Team 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNjE4NjczLCJleHAiOjE3MjE2MjU4NzN9.mvkyrk6Uu8G5ehmRaNR0X5ZRCLdz6nqND93-TjWgg14-V_jqw9Qn9wDvdbHeYs0tF2X3WGNbPZUUTJ4UXlx4hQ

### craete team
POST http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-2222",
  "teamName": "등산 모임",
  "description": "산을 사랑하는 모임",
  "maxMembers": 5,
  "monthlyFee": 15000
}

### get team information
GET http://localhost:8080/api/v1/team/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### get teams
GET http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### delete team
DELETE http://localhost:8080/api/v1/team/2/members?member_id=1&account_number=1234-1111
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### join team
POST http://localhost:8080/api/v1/team/12/members?member_id=4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### withdraw team
DELETE http://localhost:8080/api/v1/team/12/members/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}
