# Team 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNTI4MTgwLCJleHAiOjE3MjE1MzUzODB9.sCrS3kcUHWH90Ed7CowBMLxHf05Lr26jwo3iCS2TUH6jnEj67ijhpa_VjirXQyQL4_POPCBTa61R24SSodXNQA

### craete team
POST http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "teamName": "풋살 모임",
  "description": "함꼐 풋살 하실 분!!",
  "maxMembers": 10,
  "monthlyFee": 1000
}

### delete team
DELETE http://localhost:8080/api/v1/team/1?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### get team information
GET http://localhost:8080/api/v1/team/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### join team
POST http://localhost:8080/api/v1/team/2/members?member_id=4
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### withdraw team
DELETE http://localhost:8080/api/v1/team/2/members/4
Content-Type: application/json
Authorization: Bearer {{accessToken}}
