# Team 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNTE3OTQ3LCJleHAiOjE3MjE1MjUxNDd9.ZZK3TJ2gyjJP24qRCUQ-wlLoNNc5c-qbDI1zb-tFCErb4BVW899JWSFmDyD0bCj3eJtKkvd4sbqPFjkI5j2hMg

### craete team
POST http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "teamName": "풋살 모임",
  "description": "함꼐 풋살 하실 분!!",
  "maxMembers": 10,
  "monthlyFee": 1000
}

### delete team
DELETE http://localhost:8080/api/v1/team/1?member_id=1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### get team information
GET http://localhost:8080/api/v1/team/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### join team
POST http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "teamName": "풋살 모임",
  "description": "함꼐 풋살 하실 분!!",
  "maxMembers": 10,
  "fee": 1000
}

### withdraw team
POST http://localhost:8080/api/v1/team
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "teamName": "풋살 모임",
  "description": "함꼐 풋살 하실 분!!",
  "fee": 1000
}
