# Transaction 테스트

### AccessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxNDgxMjI4LCJleHAiOjE3MjE0ODg0Mjh9.LhunMjl37LLaPr9aS6bQcVw3o2fCWiGmMH3n8TeLuX85CLDIw8MQye5iwZohic4qY3flHHV3RxqZlaCDi-PQHg

# 잔액 사용 및 중복 거래 테스트
### use balance1
POST http://localhost:8080/api/v1/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "amount": 20
}

### use balance3
POST http://localhost:8080/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "memberId": 1,
  "accountNumber": "1234-1111",
  "amount": 30
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "6798598a387c4e76bad008161798f048",
  "accountNumber": "1000000000",
  "amount": 3
}

### query transaction
GET http://localhost:8080/transaction/3925a42678fb4f7898bf8e8b1f071645