# 거래 테스트
# client1 accessToken
@accessToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjbGllbnQxIiwiaWF0IjoxNzIxMzQzNTA1LCJleHAiOjE3MjEzNTA3MDV9.WSbguR0e_FZ1GGxLAv83CmnExGLQvuGIe7dcwO-N2kmB2C8D4rGIWt25VJ6Z9E_91N8EfzCW15gmAvxzGBTp5g

# 잔액 사용 및 중복 거래 테스트
### use balance1
POST http://localhost:8080/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 1,
  "accountNumber": "1234-1111",
  "amount": 10
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 1,
  "accountNumber": "1234-1111",
  "amount": 20
}

### use balance3
POST http://localhost:8080/transaction/use
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 1,
  "accountNumber": "1234-1111",
  "amount": 30
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "6798598a387c4e76bad008161798f048",
  "accountNumber": "1000000000",
  "amount": 3
}

### query transaction
GET http://localhost:8080/transaction/3925a42678fb4f7898bf8e8b1f071645