spring:
  application:
    name: gachipay

  redis:
    data:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/gachipay?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: sherlock

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: Z2FjaGlwYXktand0LXNlY3JldC1rZXkK



